/*
 * The MIT License
 *
 * Copyright 2012 shinitei.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package fenshi.ot;


import com.sun.org.apache.xalan.internal.xsltc.compiler.util.StringStack;
import java.awt.Color;
import java.util.Locale;
import javax.swing.BorderFactory;
import javax.swing.table.DefaultTableModel;
import org.multibit.controller.MultiBitController;
import org.multibit.viewsystem.View;
import org.multibit.viewsystem.swing.MultiBitFrame;
import org.multibit.viewsystem.swing.view.AddressesPanel;
import org.multibit.viewsystem.swing.view.DashedBorder;

/**
 *
 * @author shinitei
 */
public class OT_SendPanel extends javax.swing.JPanel implements View {
    
    protected MultiBitController controller;
    
    /**
     * Creates new form OT_ReceivePanel
     */
    public OT_SendPanel(MultiBitController C) {
        initComponents();
        controller = C;

        jLabel1.setText(controller.getLocaliser().getString("OT_SendPanel.titleLabel"));
        jLabel2.setText(controller.getLocaliser().getString("OT_SendPanel.adressLabel"));
        jLabel4.setText(controller.getLocaliser().getString("OT_SendPanel.labelLabel"));
        jLabel3.setText(controller.getLocaliser().getString("OT_SendPanel.amountLabel"));
        jButton1.setText(controller.getLocaliser().getString("OT.sendButton"));
        DefaultTableModel defaultTableModel = new DefaultTableModel(
                                                      new Object[][]{
                                                          {"BhD1", "zQ584ZWBqqx5CReL7eW4T8jfV7TwtbkuqG"},
                                                          {"BhD2", "ToRq17gmCdQWfenShiX46oRG35cNqrIPgB"},
                                                          {"BhD3", "UmbPn68On8Gk18bi9qVTHWF2QHcB2qVZMT"},
                                                          {"BhD4", "M6xeONp6FAqFMBLQs7MtwEe48FG8X2LWrm"}
                                                      },
                                                      new String[]{
                                                          controller.getLocaliser().getString("OT_SendPanel.tablecolumn1Title"),
                                                          controller.getLocaliser().getString("OT_SendPanel.tablecolumn2Title")
                                                      });
        Data_Table.setModel(defaultTableModel);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Upper_Panel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Middle_Panel = new AddressesPanel();
        Bottom_Panel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Data_Table = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        Upper_Panel.setBackground(new java.awt.Color(255, 255, 255));
        Upper_Panel.setBorder(BorderFactory.createMatteBorder(1, 0, 1, 0, new Color(0x8394a1)));

        jButton1.setText("Send");

        jLabel4.setText("Label");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jLabel2.setText("Adress:");

        jLabel3.setText("Amount:");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Tekst");

        javax.swing.GroupLayout Upper_PanelLayout = new javax.swing.GroupLayout(Upper_Panel);
        Upper_Panel.setLayout(Upper_PanelLayout);
        Upper_PanelLayout.setHorizontalGroup(
            Upper_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Upper_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Upper_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(Upper_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton1)
                        .addGroup(Upper_PanelLayout.createSequentialGroup()
                            .addGroup(Upper_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(Upper_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(jLabel4))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(Upper_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane2)
                                .addComponent(jTextField3)
                                .addComponent(jTextField2)))))
                .addContainerGap(261, Short.MAX_VALUE))
        );
        Upper_PanelLayout.setVerticalGroup(
            Upper_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Upper_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(Upper_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(Upper_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Upper_PanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Upper_PanelLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Upper_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        Middle_Panel.setBackground(new java.awt.Color(210, 147, 46));

        javax.swing.GroupLayout Middle_PanelLayout = new javax.swing.GroupLayout(Middle_Panel);
        Middle_Panel.setLayout(Middle_PanelLayout);
        Middle_PanelLayout.setHorizontalGroup(
            Middle_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Middle_PanelLayout.setVerticalGroup(
            Middle_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );

        Bottom_Panel.setBackground(new java.awt.Color(255, 255, 255));

        Data_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"BhD1", "zQ584ZWBqqx5CReL7eW4T8jfV7TwtbkuqG"},
                {"BhD2", "ToRq17gmCdQWfenShiX46oRG35cNqrIPgB"},
                {"BhD3", "UmbPn68On8Gk18bi9qVTHWF2QHcB2qVZMT"},
                {"BhD4", "M6xeONp6FAqFMBLQs7MtwEe48FG8X2LWrm"}
            },
            new String [] {
                "Label", "Address"
            }
        ));
        Data_Table.setShowHorizontalLines(false);
        Data_Table.setShowVerticalLines(false);
        jScrollPane1.setViewportView(Data_Table);

        javax.swing.GroupLayout Bottom_PanelLayout = new javax.swing.GroupLayout(Bottom_Panel);
        Bottom_Panel.setLayout(Bottom_PanelLayout);
        Bottom_PanelLayout.setHorizontalGroup(
            Bottom_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)
        );
        Bottom_PanelLayout.setVerticalGroup(
            Bottom_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Upper_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Middle_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Bottom_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Upper_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(Middle_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Bottom_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextField2ActionPerformed
    {//GEN-HEADEREND:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Bottom_Panel;
    private javax.swing.JTable Data_Table;
    private javax.swing.JPanel Middle_Panel;
    private javax.swing.JPanel Upper_Panel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables

    @Override
    public void displayView() {
        this.validate();
    }

    @Override
    public void updateView() {
        
    }

    @Override
    public void navigateAwayFromView(int nextViewId, int relationshipOfNewViewToPrevious) {
       
    }

    @Override
    public void displayMessage(String messageKey, Object[] messageData, String titleKey) {
        
    }
}
